CREATE TABLE orders
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    exchange_name   VARCHAR(255)                            NOT NULL,
    symbol          VARCHAR(255)                            NOT NULL,
    order_id        BIGINT                                  NOT NULL,
    client_order_id VARCHAR(255),
    side            VARCHAR(255)                            NOT NULL,
    type            VARCHAR(255)                            NOT NULL,
    executed_qty    DECIMAL(18, 8)                          NOT NULL,
    cum_quote       DECIMAL(18, 8),
    entry_price     DECIMAL(18, 8),
    exit_price      DECIMAL(18, 8),
    slippage        DECIMAL(18, 8),
    leverage        INTEGER                                 NOT NULL,
    pnl             DECIMAL(18, 8),
    status          VARCHAR(255)                            NOT NULL,
    position_side   VARCHAR(255)                            NOT NULL,
    created_at      BIGINT                                  NOT NULL,
    closed_at       BIGINT,
    updated_at      BIGINT                                  NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

ALTER TABLE orders
    ADD CONSTRAINT uc_orders_order UNIQUE (order_id);

CREATE INDEX idx_exchange_name
    ON orders (exchange_name);

CREATE INDEX idx_symbol
    ON orders (symbol);